### ISSUE TITLE
clocksy sync after connection is lost

### ISSUE THREAD

**Issue by mstdokumaci** [vigour-io/brisky-hub#195]
happens on client hub after server hub is killed.

Stack trace:

```
/Users/mustafadokumaci/vigour/test/node_modules/websocket/lib/W3CWebSocket.js:111
        throw new Error('cannot call send() while not connected');
        ^

Error: cannot call send() while not connected
    at W3CWebSocket.send (/Users/mustafadokumaci/vigour/test/node_modules/websocket/lib/W3CWebSocket.js:111:15)
    at ClocksyClient.sendRequest (/Users/mustafadokumaci/vigour/test/node_modules/brisky-hub/lib/upstream/connect.js:27:34)
    at ClocksyClient.sendAutoRequest (/Users/mustafadokumaci/vigour/test/node_modules/clocksy/lib/index.js:195:12)
    at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by jimdebeer** [comment]
hmm were working on replacing it should never happen
